apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: cgx5kx8cr-nodejs 
  janus-idp.io/tekton: cgx5kx8cr-nodejs
  backstage.io/kubernetes-id: cgx5kx8cr-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: cgx5kx8cr-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml